apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: loxa0erdo-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/loxa0erdo-dotnet-basic-gitops